### ISSUE TITLE
Images for README

### ISSUE THREAD

**Issue by veryjos** [simply-jos/darwintiler#1]
Hosting them here so they don't pollute the repo:

<img width="1920" alt="screen shot 2017-07-24 at 7 18 40 pm" src="https://user-images.githubusercontent.com/11465187/28549014-743e56d4-70a5-11e7-8285-bdc460dd984a.png">

**Comment by veryjos** [comment]
![output](https://user-images.githubusercontent.com/11465187/28549696-ddc6740c-70a9-11e7-82db-1307a2bfb8df.gif)

**Comment by dom96** [comment]
TIL about this clever way to host images on GitHub. Probably would have been good to downscale the image a bit though :)
