### ISSUE TITLE
How do I grant darwintiler accessibility permissions?

### ISSUE THREAD

**Issue by sg-s** [simply-jos/darwintiler#4]
I built the program successfully. But I don't know how to add darwintiler to the list of apps that can control this computer. Help?

**Comment by dom96** [comment]
You should be able to do it in this preferences dialog:

<img width="780" alt="screen shot 2017-08-04 at 19 04 27" src="https://user-images.githubusercontent.com/246651/28981011-c8fbf122-7947-11e7-803c-031b2f310133.png">

**Comment by sg-s** [comment]
thanks -- i got this far. and then? Do I press the "+"? How do I tell the OS I want to allow darwintiler to control my computer?

**Comment by dom96** [comment]
Yes, you probably can't go wrong here. Just play around in this dialog until it works :)

**Comment by sg-s** [comment]
sorry, that isn't helpful at all.

**Comment by veryjos** [comment]
If I recall correctly, on MacOS, you can no longer select CLI apps in that dialog. I'll have to make an easier way to allow accessibility permissions.

**Comment by superfunc** [comment]
I believe @simply-jos is correct here, this is probably what is causing @sg-s ' confusion (assuming they are on sierra).

**Comment by sg-s** [comment]
Yes, I'm on Sierra.

**Comment by handsomematt** [comment]
```
sudo sqlite3 "/Library/Application Support/com.apple.TCC/TCC.db" 'INSERT INTO access VALUES("kTCCServiceAccessibility","/Users/matt/dev/darwintiler/build/darwintiler",1,1,1,NULL,NULL)'
```

this will add the entry manually

edit:

although even with that AXIsProcessTrusted() returns false.

**Comment by veryjos** [comment]
As a workaround, you can use a tool like macappshell to generate a .app file for the program or just stick your entire terminal emulator's .app in there and invoke it from the terminal (which is probably a bad idea, but will work).
